export interface challongeGame {
    id: number,
    tournament_id: number,
    state: string,
    player1_id: number,
    player2_id: number,
    player1_prereq_match_id: number,
    player2_prereq_match_id: number,
    player1_is_prereq_match_loser: boolean,
    player2_is_prereq_match_loser: boolean,
    winner_id: number,
    loser_id: number,
    started_at: string,
    ended_at: string,
    updated_at: string,
    identifier: string,
    has_attachment: boolean,
    round: number,
    player1_votes: number,
    player2_votes: number,
    group_id: number,
    scheduled_time: string,
    location: string,
    underway_at: string,
    forfeited: boolean
    prerequisite_match_ids_csv: string,
    scores_csv: string,
}