export interface Recommendation {
    osuid: number,
    mapid: string,
    title: string,
    artist: string,
    version: string,
    creator: string,
    cover: string,
    maxCombo: number,
    mode: string,
    mods: Array<string>,
    drain: number,
    length: number,
    acc95: number,
    acc97: number,
    acc99: number,
    acc100: number,
    ar: number,
    od: number,
    cs: number,
    hp: number,
    bpm: number,
    star: number,
    score: number
}