export interface Recommendation {
    osuid: Number,
    mapid: String,
    title: String,
    artist: String,
    version: String,
    creator: String,
    cover: String,
    maxCombo: Number,
    mode: String,
    mods: Array<String>,
    drain: Number,
    length: Number,
    acc95: Number,
    acc97: Number,
    acc99: Number,
    acc100: Number,
    ar: Number,
    od: Number,
    cs: Number,
    hp: Number,
    bpm: Number,
    star: Number,
    score: Number
}